In [8]:
import fastf1
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [9]:
import sys

sys.path.append("../")

from src.data_loader import (
    load_race_session,
    get_laps
)

session = load_race_session(
    2024,
    "Monza",
    "R"
)

laps = get_laps(session)

laps.head()

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:18.931000,LEC,16,0 days 00:01:28.179000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:29.989000,...,True,Ferrari,0 days 00:55:50.494000,2024-09-01 13:03:34.413,1,2.0,False,,False,False
1,0 days 00:58:44.327000,LEC,16,0 days 00:01:25.396000,2.0,1.0,NaT,NaT,0 days 00:00:27.707000,0 days 00:00:29.265000,...,True,Ferrari,0 days 00:57:18.931000,2024-09-01 13:05:02.850,1,2.0,False,,False,True
2,0 days 01:00:09.506000,LEC,16,0 days 00:01:25.179000,3.0,1.0,NaT,NaT,0 days 00:00:27.679000,0 days 00:00:29.001000,...,True,Ferrari,0 days 00:58:44.327000,2024-09-01 13:06:28.246,1,2.0,False,,False,True
3,0 days 01:01:34.316000,LEC,16,0 days 00:01:24.810000,4.0,1.0,NaT,NaT,0 days 00:00:27.653000,0 days 00:00:28.883000,...,True,Ferrari,0 days 01:00:09.506000,2024-09-01 13:07:53.425,1,2.0,False,,False,True
4,0 days 01:02:58.919000,LEC,16,0 days 00:01:24.603000,5.0,1.0,NaT,NaT,0 days 00:00:27.630000,0 days 00:00:28.790000,...,True,Ferrari,0 days 01:01:34.316000,2024-09-01 13:09:18.235,1,2.0,False,,False,True

In [10]:
from src.analysis import (
    get_best_laps,
    get_average_race_pace,
    get_driver_statistics
)

In [11]:
best_laps = get_best_laps(laps)

best_laps.head(10)

Driver
NOR   0 days 00:01:21.432000
HAM   0 days 00:01:21.512000
VER   0 days 00:01:21.745000
PIA   0 days 00:01:21.943000
RUS   0 days 00:01:22.036000
STR   0 days 00:01:22.232000
ALO   0 days 00:01:22.944000
PER   0 days 00:01:22.971000
SAI   0 days 00:01:23.219000
LEC   0 days 00:01:23.226000
Name: LapTime, dtype: timedelta64[ns]

In [12]:
race_pace = get_average_race_pace(laps)

race_pace.head(10)

Driver
PIA      0 days 00:01:23.542000
NOR   0 days 00:01:23.607604166
HAM   0 days 00:01:23.897270833
LEC      0 days 00:01:23.949360
RUS   0 days 00:01:23.983666666
VER      0 days 00:01:24.124375
SAI      0 days 00:01:24.236080
PER   0 days 00:01:24.499208333
ALO   0 days 00:01:24.687021276
MAG   0 days 00:01:24.916877551
Name: LapTime, dtype: timedelta64[ns]

In [13]:
stats = get_driver_statistics(laps)

stats.head(10)

                            mean                       std  count
Driver
PIA       0 days 00:01:23.542000 0 days 00:00:00.951408273     48
NOR    0 days 00:01:23.607604166 0 days 00:00:01.044424747     48
HAM    0 days 00:01:23.897270833 0 days 00:00:01.183427059     48
LEC       0 days 00:01:23.949360 0 days 00:00:00.629429374     50
RUS    0 days 00:01:23.983666666 0 days 00:00:01.175278515     48
VER       0 days 00:01:24.124375 0 days 00:00:01.121262977     48
SAI       0 days 00:01:24.236080 0 days 00:00:00.783034933     50
PER    0 days 00:01:24.499208333 0 days 00:00:01.013597237     48
ALO    0 days 00:01:24.687021276 0 days 00:00:00.978855997     47
MAG    0 days 00:01:24.916877551 0 days 00:00:00.850925247     49